param(
    [Parameter(Mandatory=$true)][string]$SdkBin,
    [string]$GameDir = "$PSScriptRoot\..\..\sp\game\mod_episodic"
)
$ErrorActionPreference = 'Stop'
$SdkBin = (Resolve-Path -LiteralPath $SdkBin).Path
$GameDir = (Resolve-Path -LiteralPath $GameDir).Path
$compiler = Join-Path $SdkBin 'shadercompile.exe'
if (!(Test-Path -LiteralPath $compiler)) { throw "Missing $compiler" }
$source = (Resolve-Path -LiteralPath "$PSScriptRoot\..\..\sp\src\materialsystem\stdshaders\bs2_tiltshift_ps20b.fxc").Path
$stage = Join-Path $PSScriptRoot 'shader-build'
New-Item -ItemType Directory -Force -Path $stage | Out-Null
New-Item -ItemType Directory -Force -Path (Join-Path $stage 'shaders\fxc') | Out-Null
Copy-Item -LiteralPath $source -Destination $stage
Copy-Item -LiteralPath "$PSScriptRoot\..\..\sp\src\dx9sdk\utilities\dx_proxy.dll" -Destination $stage
# One fixed combination. Format comes from this SDK's fxc_prep.pl.
@'
**** generated by BS2 build_shader.ps1 ****
#BEGIN bs2_tiltshift_ps20b
bs2_tiltshift_ps20b.fxc
#DEFINES-D:
#DEFINES-S:
#SKIP:
0
#COMMAND:
fxc.exe /DTOTALSHADERCOMBOS=1 /DCENTROIDMASK=0 /DNUMDYNAMICCOMBOS=1 /DFLAGS=0x0
/Tps_2_b /DSHADER_MODEL_PS_2_B=1 /nologo /Foshader.o bs2_tiltshift_ps20b.fxc>output.txt 2>&1
#END
**** end ****
'@ | Set-Content -LiteralPath (Join-Path $stage 'filelist.txt') -Encoding ascii
@('bs2_tiltshift_ps20b.fxc','dx_proxy.dll',"$SdkBin\shadercompile.exe", "$SdkBin\shadercompile_dll.dll", "$SdkBin\tier0.dll", "$SdkBin\vstdlib.dll") |
    Set-Content -LiteralPath (Join-Path $stage 'uniquefilestocopy.txt') -Encoding ascii
$started = Get-Date
Push-Location $stage
try {
    & $compiler -nompi -nop4 -game $GameDir -shaderpath $stage -allowdebug
    if ($LASTEXITCODE -ne 0) { throw "shadercompile failed: $LASTEXITCODE" }
} finally { Pop-Location }
$compiled = Join-Path $stage 'shaders\fxc\bs2_tiltshift_ps20b.vcs'
if (!(Test-Path -LiteralPath $compiled)) { throw 'No VCS produced; inspect shader-build/output.txt and compiler output.' }
if ((Get-Item -LiteralPath $compiled).LastWriteTime -lt $started) { throw 'Compiler did not produce a fresh VCS.' }
$destination = Join-Path $GameDir 'shaders\fxc'
New-Item -ItemType Directory -Force -Path $destination | Out-Null
Copy-Item -LiteralPath $compiled -Destination $destination
Write-Output "Compiled shader installed in $destination"
