name: SP_Windows_TiltShift

on:
  workflow_dispatch:
  push:
    paths:
      - '.github/**'
      - 'sp/src/**'
      - 'tools/tiltshift/**'
      - 'sp/game/mod_episodic/**'
  pull_request:
   paths:
      - 'sp/src/**'
      - 'tools/tiltshift/**'
      - 'sp/game/mod_episodic/**'
      - '.github/workflows/SP_windows.yml'

jobs:
  build:
    runs-on:
      windows-2022

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Configure dependencies
        uses: ilammy/msvc-dev-cmd@v1
        with:
          arch: x86

      - name: Locate MSBuild
        uses: microsoft/setup-msbuild@v2

      - name: Build and verify DLLs
        run: ./tools/tiltshift/build_client.ps1

      - name: Upload product
        uses: actions/upload-artifact@v4
        with:
          name: bs2_tiltshift_episodic_windows
          path: |
            sp/game/mod_episodic/bin/*.dll
            sp/game/mod_episodic/materials/effects/bs2_tiltshift.vmt
            sp/game/mod_episodic/shaders/fxc/bs2_tiltshift_ps20b.vcs
            sp/game/mod_episodic/cfg/bs2_tiltshift_*.cfg
          if-no-files-found: error

