name: SP_Windows_TiltShift

on:
  push:
    paths:
      - '.github/**'
      - 'sp/src/**'
      - 'sp/game/mod_episodic/**'
  pull_request:
   paths:
      - 'sp/src/**'
      - 'sp/game/mod_episodic/**'
      - '.github/workflows/SP_windows.yml'

jobs:
  build:
    runs-on:
      windows-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Configure dependencies
        uses: ilammy/msvc-dev-cmd@v1
        with:
          arch: x86

      - name: Locate MSBuild
        uses: microsoft/setup-msbuild@v2

      - name: Create project
        working-directory: sp/src
        run: devtools/bin/vpc.exe /episodic /2013 +game /mksln bs2_tiltshift.sln

      - name: Build project
        working-directory: sp/src
        run: msbuild bs2_tiltshift.sln /m:2 /p:Configuration=Release /p:Platform=Win32 /p:WindowsTargetPlatformVersion=10.0 /verbosity:minimal

      - name: Upload product
        uses: actions/upload-artifact@v4
        with:
          name: bs2_tiltshift_episodic_windows
          path: |
            sp/game/mod_episodic/bin/*.dll
            sp/game/mod_episodic/materials/effects/bs2_tiltshift.vmt
            sp/game/mod_episodic/shaders/fxc/bs2_tiltshift_ps20b.vcs
            sp/game/mod_episodic/cfg/bs2_tiltshift_*.cfg
          if-no-files-found: error
